services:
  - type: web
    name: fastapi-service
    env: python
    plan: free
    region: oregon
    rootDirectory: /opt/render/project/src  # Pointing to 'src' folder 
    buildCommand: "pip install -r requirements.txt"
    # buildCommand: pip install -r requirements.txt 
    # startCommand: "gunicorn app:app --bind 0.0.0.0:10000"
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port ~10000  # Use src.app as the entry point 
    autoDeploy: true

 
